### PR TITLE
feat(umd) Implement Universal Module Definition pattern #626

### PR DESCRIPTION
**Pull request by ghoullier**
Hi!

This PR is associated to issue #626 

Implement UMD allow full Global, CommonJS and AMD support.

### CODE REVIEW

**Comment by ghoullier** [comment]
Hi!

I've updated my branch to support your last updates.

What do you think about this PR?

**Comment by sbordet** [comment]
I don't understand it :)

Let's start simple so that I can follow.

When CometD wanted to support AMD, it had to wrap the code for the extensions, adding some code to "sniff" for AMD. See for example [this extension](https://github.com/cometd/cometd/blob/master/cometd-javascript/common/src/main/webapp/org/cometd/TimeStampExtension.js).

However, the main file, `cometd.js` is not wrapped in this way, because it is built by concatenating other files. Would be trivial to wrap it in that way, however, by adding a little code.
It just was not done at the time because the little sniffing at the bottom was enough.

Now, let's imagine that all built files (`cometd.js` and extensions) are wrapped that way, with AMD sniffing and a fallback.

What you would like to have is to add some UMD sniffing following the pattern described [here](https://github.com/umdjs/umd), in particular the `commonjsStrict` version.
Did I understand correctly ?

**Comment by sbordet** [comment]
@ghoullier bump ? will be great if we can include this in 3.1.0.

**Comment by ghoullier** [comment]
Hi! 

Yes all files must includes UMD wrapper with correct dependencies.

For classic build (aka non AMD/CommonJS), users will continue to respect include files order.

**Comment by sbordet** [comment]
UMD support has been implemented as part of #649. Thanks !

**Pull request closed without merging**
