### PR TITLE
Bower jquery

### PR DESCRIPTION
**Pull request by calbazasebastian**
I've seen that there is already a cometd-jquery,git://github.com/cometd/cometd.git component registered, but there is no bower.json file.

### CODE REVIEW

**Comment by lordkada** [comment]
No news on this issue?

**Comment by lordkada** [comment]
@sbordet do you have any plan to support `bower` for the Javascript distribution? Thanks in advance!

**Comment by sbordet** [comment]
Yes, we'll support bower. I'll look into it as soon as I have time. Thanks !

**Comment by lordkada** [comment]
Great! Many thanks... ciao!

**Comment by lordkada** [comment]
@sbordet in the meantime I've cloned the repo from @calbazasebastian (who proposed the bower initial conf) and upgraded the jquery js library to be 3.0.5 (I've sent him a couple of pull requests...). You can find my repo here: [https://github.com/lordkada/cometd-javascript-bower](https://github.com/lordkada/cometd-javascript-bower)

**Comment by sbordet** [comment]
Bower support has been integrated in CometD 3.1, which is now published at https://bower.io.

**Pull request closed without merging**
