### PR TITLE
Fixed null reference

### PR DESCRIPTION
**Pull request by lmartorella**
Hello,
We found a couple of points in which the Javascript client can fail during transport issues. I can see that there was fixes in the past about such checks, and I would like to add a couple of additional checks that I observed sporadically (unfortunately I'm not able to replicate them).
Can you please let us know if the fixes are legit?

Thanks, L

### CODE REVIEW

**Comment by sbordet** [comment]
@lmartorella the DCO check did not pass, and apparently there are 250 commits in this PR, and 218 modified files.
Please close this one, and recreate one with the proper fixes and DCO.
Thanks!

**Comment by lmartorella** [comment]
Hello, just fixed the base branch and switched to the 8.0.x (I suppose this is the main one): it has wrongly picked up the 6.0.x because it is the default one I think. The commit is only one.
Thx, L

**Comment by sbordet** [comment]
@lmartorella you need to rebase your changes against the latest version of the code.

**Review by sbordet — APPROVED** [review]

**Comment by sbordet** [comment]
@lmartorella Thanks!

**Pull request merged**
