### PR TITLE
Fix throw without stack

### PR DESCRIPTION
**Pull request by lmartorella**
Hello,
As stated in the MDN documentation "just about any object can be thrown in JavaScript. Nevertheless, not all thrown objects are created equal. While it is common to throw numbers or strings as errors, it is frequently more effective to use one of the exception types specifically created for this purpose".

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Control_flow_and_error_handling

Since the stack trace is captured when a `Error` object is created, it would be better to always throw error objects in order to let the application to be able to recover the stack for issue analysis.

The MR so changes all the throw statement in the code adding the Error constructor.

Thanks, L

### CODE REVIEW

**Comment by sbordet** [comment]
@lmartorella the DCO check did not pass, and apparently there are 250 commits in this PR.
Please close this one, and recreate one with the proper fixes and DCO.
Thanks!

**Comment by lmartorella** [comment]
Hello, just fixed the base branch and switched to the 8.0.x (I suppose this is the main one): it has wrongly picked up the 6.0.x because it is the default one I think. The commit is only one.
Thx, L

**Comment by sbordet** [comment]
@lmartorella you need to rebase your changes against the latest version of the code.

**Review by sbordet — APPROVED** [review]

**Comment by sbordet** [comment]
@lmartorella Thanks!

**Pull request merged**
