### PR TITLE
[WIP] use pipeline version of junit to have a label on jdk/cometd and parallel build

### PR DESCRIPTION
**Pull request by olamy**
…ailure

Signed-off-by: olivier lamy <olamy@apache.org>

### CODE REVIEW

**Comment by olamy** [comment]
@sbordet to test the Jenkinsfile in our CI you need to add me as a collaborator at least.

**Comment by sbordet** [comment]
@olamy please:

- no spaces after parenthesis in `if` or function calls
- braces at the end of the line

I thought you were `root` on Jenkins and could do anything.
Where do I need to add you as collaborator ?

**Comment by olamy** [comment]
@sbordet as I'm not collaborator in cometd project, Jenkins do not qualify me as a trusted source so it will not test my new Jenkinsfile with our Jenkins instance.

**Comment by sbordet** [comment]
@olamy I merged your changes.

However, the CometD builds for different Jetty versions cannot run in parallel.
For example, the build for Jetty 9.2.x cannot run in parallel with the build for Jetty 9.3.x.

This is because at some point the CometD build runs the tests for the clustering features of CometD, and the test will check for the expected number of nodes, which will obviously fail is there is another build that start other nodes.

Let me know your thoughts.

**Comment by olamy** [comment]
@sbordet shouldn't be a problem as parallel build means different jenkins node (i.e docker pod)

**Pull request merged**
